2024.06.03 14:18:47 ERROR: C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\utils\log.py Internal Server Error: /news/ (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news/post_list.html'), <traceback object at 0x0000028089052800>)
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2024.06.03 14:18:47 ERROR: C:\Users\1\PycharmProjects\NewsPoptal\venv\Lib\site-packages\django\core\servers\basehttp.py "GET /news/?page=2 HTTP/1.1" 500 87513 None
